dist: xenial    # for 3.7 support
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip3 install -r requirements.txt
script:
  - pytest
deploy:
  provider: pypi
  user: theaustinator
  server: https://test.pypi.org/legacy/
  on:
    branch: production